/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KvmSpinner {
    }
    interface KvmStockFind {
    }
    interface KvmStockPrice {
        "stockDefault": string;
    }
}
declare global {
    interface HTMLKvmSpinnerElement extends Components.KvmSpinner, HTMLStencilElement {
    }
    var HTMLKvmSpinnerElement: {
        prototype: HTMLKvmSpinnerElement;
        new (): HTMLKvmSpinnerElement;
    };
    interface HTMLKvmStockFindElement extends Components.KvmStockFind, HTMLStencilElement {
    }
    var HTMLKvmStockFindElement: {
        prototype: HTMLKvmStockFindElement;
        new (): HTMLKvmStockFindElement;
    };
    interface HTMLKvmStockPriceElement extends Components.KvmStockPrice, HTMLStencilElement {
    }
    var HTMLKvmStockPriceElement: {
        prototype: HTMLKvmStockPriceElement;
        new (): HTMLKvmStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "kvm-spinner": HTMLKvmSpinnerElement;
        "kvm-stock-find": HTMLKvmStockFindElement;
        "kvm-stock-price": HTMLKvmStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface KvmSpinner {
    }
    interface KvmStockFind {
        "onUcSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface KvmStockPrice {
        "stockDefault"?: string;
    }
    interface IntrinsicElements {
        "kvm-spinner": KvmSpinner;
        "kvm-stock-find": KvmStockFind;
        "kvm-stock-price": KvmStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kvm-spinner": LocalJSX.KvmSpinner & JSXBase.HTMLAttributes<HTMLKvmSpinnerElement>;
            "kvm-stock-find": LocalJSX.KvmStockFind & JSXBase.HTMLAttributes<HTMLKvmStockFindElement>;
            "kvm-stock-price": LocalJSX.KvmStockPrice & JSXBase.HTMLAttributes<HTMLKvmStockPriceElement>;
        }
    }
}
