/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KvmStockPrice {
    }
}
declare global {
    interface HTMLKvmStockPriceElement extends Components.KvmStockPrice, HTMLStencilElement {
    }
    var HTMLKvmStockPriceElement: {
        prototype: HTMLKvmStockPriceElement;
        new (): HTMLKvmStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "kvm-stock-price": HTMLKvmStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface KvmStockPrice {
    }
    interface IntrinsicElements {
        "kvm-stock-price": KvmStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kvm-stock-price": LocalJSX.KvmStockPrice & JSXBase.HTMLAttributes<HTMLKvmStockPriceElement>;
        }
    }
}
